// <auto-generated />
using Article.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Article.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220420193852_db")]
    partial class db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Article.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "fa-mobile-screen",
                            Name = "TELEFON"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "fa-computer",
                            Name = "BİLGİSAYAR"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "fa-tv",
                            Name = "TELEVİZYON"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "fa-camera",
                            Name = "KAMERA"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "fa-blender",
                            Name = "BEYAZ EŞYA"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "fa-chair",
                            Name = "EV ALETLERİ"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "fa-spray-can-sparkles",
                            Name = "BAKIM"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "fa-gamepad",
                            Name = "OYUN"
                        });
                });

            modelBuilder.Entity("Article.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Oppo"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Iphone"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Huawei"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "HP"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Lenova"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "LG"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Grundig"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Name = "makine 1"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Name = "makine 2"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "makine 3"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Name = "Buzdolabı"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Name = "Çamaşır Makinası"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Name = "Fırın"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Name = "Ev Aleti 1"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Name = "Ev Aleti 2"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Name = "Ev Aleti 3"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            Name = "Bakım Sağlık"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            Name = "Bakım Sağlık2"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            Name = "Bakım Sağlık3"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            Name = "Spor"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            Name = "Spor2"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 8,
                            Name = "Spor3"
                        });
                });

            modelBuilder.Entity("Article.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sefa@sefa",
                            password = "sefa"
                        });
                });

            modelBuilder.Entity("Article.Models.Product", b =>
                {
                    b.HasOne("Article.Models.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Article.Models.Category", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
