// <auto-generated />
using Article.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Article.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Article.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "fa-mobile-screen",
                            Name = "TELEFON"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "fa-computer",
                            Name = "BİLGİSAYAR"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "fa-tv",
                            Name = "TELEVİZYON"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "fa-camera",
                            Name = "KAMERA"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "fa-blender",
                            Name = "BEYAZ EŞYA"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "fa-chair",
                            Name = "EV ALETLERİ"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "fa-spray-can-sparkles",
                            Name = "BAKIM"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "fa-gamepad",
                            Name = "OYUN"
                        });
                });

            modelBuilder.Entity("Article.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sefa@sefa",
                            password = "sefa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
